# **Connect to Drive**

In [71]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [72]:
# untuk mount gdrive
!pip install -U -q PyDrive

In [73]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth

# untuk kasih akses ke gdrive
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# **Import Library**

In [74]:
!pip install facebook-scraper

In [75]:
from facebook_scraper import get_posts
import requests

import csv
import pandas as pd 
from pandas import DataFrame
import numpy as np

In [76]:
import nltk
nltk.download('punkt')

!pip install Sastrawi

from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory, StopWordRemover, ArrayDictionary
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

import re
import string

# impor word_tokenize dari modul nltk
from nltk.tokenize import word_tokenize
# impor untuk memunculkan frequensi kemunculan kata
from nltk.probability import FreqDist

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [77]:
# Objek Datetime
from datetime import datetime, timedelta
# Perhitungan Akurasi
from sklearn.metrics import accuracy_score
# min-max normalization
from sklearn import preprocessing

In [78]:
import nltk
nltk.download('punkt')

!pip install Sastrawi

from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory, StopWordRemover, ArrayDictionary
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

import re
import string

# impor word_tokenize dari modul nltk
from nltk.tokenize import word_tokenize
# impor untuk memunculkan frequensi kemunculan kata
from nltk.probability import FreqDist

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


# **Get Data**

## **Get All Post**

> Get data from Facebook Kementrian Kesehatan RI


In [ ]:
datas=[]
for post in get_posts('KementerianKesehatanRI', pages=3):
  datas.append(post)

In [ ]:
post = DataFrame(datas)
# post

post_id  ...                                             images
0  4036440916385978  ...  [https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9...
1  4035981553098581  ...  [https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9...
2  4035546473142089  ...  [https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9...
3  4035064956523574  ...  [https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9...
4  4033728346657235  ...  [https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9...
5  4033473680016035  ...                                                 []
6  4033118980051505  ...  [https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9...
7  4032929890070414  ...                                                 []
8  4032908823405854  ...  [https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9...
9  4032664880096915  ...                                                 []

[10 rows x 16 columns]

In [ ]:
# Simpan dalam bentuk CSV

# post.to_csv('/content/drive/My Drive/Project Sistem Pakar/Dataset/posts.csv', index=False)

## **Get Comment Detail**

In [ ]:
# get csv untuk comment, csv ada di gdrive, diambil dengan menggunakan facepager

raw_comment = pd.read_csv('drive/My Drive/Project Sistem Pakar/Dataset/raw_comments.csv', sep=';')
print('Jumlah Raw Komen: ', len(raw_comment))

Jumlah Raw Komen:  2512


In [ ]:
raw_comment

path  ...  like_count
0                      662119780484792_4004976832865720  ...         NaN
1     662119780484792_4004976832865720/4004976832865...  ...        34.0
2     662119780484792_4004976832865720/4004976832865...  ...        22.0
3     662119780484792_4004976832865720/4004976832865...  ...        16.0
4     662119780484792_4004976832865720/4004976832865...  ...        19.0
...                                                 ...  ...         ...
2507  662119780484792_4004976832865720/6621197804847...  ...         0.0
2508  662119780484792_4004976832865720/6621197804847...  ...         0.0
2509  662119780484792_4004976832865720/6621197804847...  ...         1.0
2510  662119780484792_4004976832865720/6621197804847...  ...         NaN
2511  662119780484792_4004976832865720/6621197804847...  ...         NaN

[2512 rows x 13 columns]

In [ ]:
# Preprocessing - mengambil data yang diperlukan saja dari hasil csv yang dilakukan di facepager

raw_comment = raw_comment.dropna()
raw_comment['post_id'] = raw_comment['object_id'].astype(str).str[0:16]
raw_comment['comment_id'] = raw_comment['object_id'].astype(str).str[17:]
raw_comment = raw_comment[['post_id', 'comment_id', 'message', 'created_time']]

# raw_comment.to_csv('drive/My Drive/Project Sistem Pakar/Dataset/comments.csv', index=False)

print('Jumlah komen setelah preprocessing: ', len(raw_comment))
raw_comment

Jumlah komen setelah preprocessing:  2280


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


post_id  ...              created_time
1     4004976832865720  ...  2020-11-28T12:11:41+0000
2     4004976832865720  ...  2020-11-28T12:16:15+0000
3     4004976832865720  ...  2020-11-28T15:33:11+0000
4     4004976832865720  ...  2020-11-28T12:10:16+0000
5     4004976832865720  ...  2020-11-29T00:57:02+0000
...                ...  ...                       ...
2505  4000645779965492  ...  2020-11-27T10:53:33+0000
2506  4000645779965492  ...  2020-11-27T05:24:41+0000
2507  4000645779965492  ...  2020-11-27T16:43:23+0000
2508  4000645779965492  ...  2020-11-27T10:43:37+0000
2509  4000645779965492  ...  2020-11-27T09:27:35+0000

[2280 rows x 4 columns]

## **Combined Data**

In [ ]:
posts = pd.read_csv('drive/My Drive/Project Sistem Pakar/Dataset/posts.csv')
print('Jumlah Berita: ', len(posts))
posts.head()

Jumlah Berita:  10


post_id  ...                                             images
0  4004976832865720  ...  ['https://scontent-hkt1-1.xx.fbcdn.net/v/t1.0-...
1  4004494309580639  ...                                                 []
2  4004417006255036  ...                                                 []
3  4004358039594266  ...                                                 []
4  4003974322965971  ...                                                 []

[5 rows x 16 columns]

In [ ]:
comments = pd.read_csv('drive/My Drive/Project Sistem Pakar/Dataset/comments.csv')
print('Jumlah Komen: ', len(comments))
comments.tail()

Jumlah Komen:  2280


post_id  ...              created_time
2275  4000645779965492  ...  2020-11-27T10:53:33+0000
2276  4000645779965492  ...  2020-11-27T05:24:41+0000
2277  4000645779965492  ...  2020-11-27T16:43:23+0000
2278  4000645779965492  ...  2020-11-27T10:43:37+0000
2279  4000645779965492  ...  2020-11-27T09:27:35+0000

[5 rows x 4 columns]

In [ ]:
post_set = set(comments['post_id'].astype(str))
print('Jumlah berita: ', len(post_set))

Jumlah berita:  10


In [ ]:
for i in post_set:
  msg = comments[comments['post_id'].astype(str) == i]['message'][:10].tolist()
  msg = ' $$$ '.join(msg)
  posts.loc[posts['post_id'].astype(str) == i, 'comments_msg'] = msg

print('Jumlah komen setiap berita: ', len(posts['comments_msg']))
posts

Jumlah komen setiap berita:  10


post_id  ...                                       comments_msg
0  4004976832865720  ...  Pemerintah sudah berusaha semaksimal mungkin m...
1  4004494309580639  ...  Tetap semangat dan berpikir positif banyak ber...
2  4004417006255036  ...  Tetap semangat dan berpikir positif banyak ber...
3  4004358039594266  ...  Terima kasih banyak atas semua ini tetap  berf...
4  4003974322965971  ...  Kerja bagus yg patut dicontoh, sehat Bali seha...
5  4003663296330407  ...  Tetap Waspada jaga kesehatan ikuti protokol sa...
6  4002335383129865  ...  Bersama rakyat TNI kuat. Tiada daya dan kekuat...
7  4001694956527241  ...  Tetap Waspada jaga kesehatan ikuti protokol sa...
8  4001626216534115  ...  Terima kasih banyak atas semua ini tetap  berf...
9  4000645779965492  ...  Tetap semangat dan berpikir positif banyak ber...

[10 rows x 17 columns]

In [ ]:
posts['comments_msg'][0]

'Pemerintah sudah berusaha semaksimal mungkin memutus mata rantai virus bahkan sampai geram menangani pandemi ini...Tinggal kitanya sebagai masyarakat mari kita bantu pemerintah kita. Jangan saling menyalahkan! Dimulai dari diri kita sendiri jaga kesehatan🙏 $$$ Tetap semangat dan berpikir Positif banyak berdoa semoga pandemi ini gk cepat berakhir.... terutama buat Para medis pengorbanan Kalian Begitu luar biasa dan berjasa berada di garda Paling depan Semoga Allah selalu melindungi kalian Amin \U0001f932 $$$ Banyak orang meninggal bukan karena Corona...mungkin karena penyakit lain...dan di tambah lagi karena kemiskinan masyarkt bnyak nganggur,usaha usaha bangkrut ,cari kerja susah...hutang negara semakin banyak ...Setau saya orang yg di nyatakan pisitip Corona cuma di karantina di kasih makan minum enak bergizi...ga usah di beri obat nanti juga sembuh sendiri / negatif...suhu tubuhpun normal ,ga panas ga batuk .....kyk org ga sakit... $$$ Terima kasih banyak atas semua ini tetap  berfi

In [ ]:
# Simpan dalam bentuk CSV 

# posts.to_csv('drive/My Drive/Project Sistem Pakar/Dataset/raw_data.csv')

# **Read Dataset**

In [22]:
posts = pd.read_csv('drive/My Drive/Project Sistem Pakar/Dataset/posts.csv')
comments = pd.read_csv('drive/My Drive/Project Sistem Pakar/Dataset/comments.csv')

raw_data = pd.read_csv('drive/My Drive/Project Sistem Pakar/Dataset/raw_data.csv')

In [23]:
posts.head()

post_id  ...                                             images
0  4004976832865720  ...  ['https://scontent-hkt1-1.xx.fbcdn.net/v/t1.0-...
1  4004494309580639  ...                                                 []
2  4004417006255036  ...                                                 []
3  4004358039594266  ...                                                 []
4  4003974322965971  ...                                                 []

[5 rows x 16 columns]

In [24]:
comments

post_id  ...              created_time
0     4004976832865720  ...  2020-11-28T12:11:41+0000
1     4004976832865720  ...  2020-11-28T12:16:15+0000
2     4004976832865720  ...  2020-11-28T15:33:11+0000
3     4004976832865720  ...  2020-11-28T12:10:16+0000
4     4004976832865720  ...  2020-11-29T00:57:02+0000
...                ...  ...                       ...
2275  4000645779965492  ...  2020-11-27T10:53:33+0000
2276  4000645779965492  ...  2020-11-27T05:24:41+0000
2277  4000645779965492  ...  2020-11-27T16:43:23+0000
2278  4000645779965492  ...  2020-11-27T10:43:37+0000
2279  4000645779965492  ...  2020-11-27T09:27:35+0000

[2280 rows x 4 columns]

In [25]:
# removing duplicates if any

df = raw_data.drop_duplicates()
df = raw_data.reset_index(drop=True)
df.head()

Unnamed: 0  ...                                       comments_msg
0           0  ...  Pemerintah sudah berusaha semaksimal mungkin m...
1           1  ...  Tetap semangat dan berpikir positif banyak ber...
2           2  ...  Tetap semangat dan berpikir positif banyak ber...
3           3  ...  Terima kasih banyak atas semua ini tetap  berf...
4           4  ...  Kerja bagus yg patut dicontoh, sehat Bali seha...

[5 rows x 18 columns]

In [26]:
# drop unused data
col = ['Unnamed: 0', 'shared_text', 'image',	'video',	'video_thumbnail', 'video_id', 'post_url', 'link', 'user_id', 'images']
df.drop(col, inplace=True, axis=1)
df.head()

post_id  ...                                       comments_msg
0  4004976832865720  ...  Pemerintah sudah berusaha semaksimal mungkin m...
1  4004494309580639  ...  Tetap semangat dan berpikir positif banyak ber...
2  4004417006255036  ...  Tetap semangat dan berpikir positif banyak ber...
3  4004358039594266  ...  Terima kasih banyak atas semua ini tetap  berf...
4  4003974322965971  ...  Kerja bagus yg patut dicontoh, sehat Bali seha...

[5 rows x 8 columns]

In [27]:
raw_data

Unnamed: 0  ...                                       comments_msg
0           0  ...  Pemerintah sudah berusaha semaksimal mungkin m...
1           1  ...  Tetap semangat dan berpikir positif banyak ber...
2           2  ...  Tetap semangat dan berpikir positif banyak ber...
3           3  ...  Terima kasih banyak atas semua ini tetap  berf...
4           4  ...  Kerja bagus yg patut dicontoh, sehat Bali seha...
5           5  ...  Tetap Waspada jaga kesehatan ikuti protokol sa...
6           6  ...  Bersama rakyat TNI kuat. Tiada daya dan kekuat...
7           7  ...  Tetap Waspada jaga kesehatan ikuti protokol sa...
8           8  ...  Terima kasih banyak atas semua ini tetap  berf...
9           9  ...  Tetap semangat dan berpikir positif banyak ber...

[10 rows x 18 columns]

In [28]:
# check if any null
df.isnull().sum()

post_id         0
text            0
post_text       0
time            0
likes           0
comments        0
shares          0
comments_msg    0
dtype: int64

# **Preprocessing Data**

In [29]:
stop_factory = StopWordRemoverFactory().get_stop_words() #load default stopword

In [30]:
# kata singkatan ambil dari https://github.com/ramaprakoso/analisis-sentimen/blob/master/kamus/kbba.txt
kbba = pd.read_csv('drive/My Drive/Project Sistem Pakar/Dataset/kbba.csv')

In [31]:
more_stopword = [] #menambahkan stopword

for i in range(len(kbba['Singkatan'])):
  review = kbba['Singkatan'][i]
  more_stopword.append(review)

In [32]:
print(more_stopword)

['7an', '@', 'aamin', 'aammiiaamiinn', 'ababil', 'abis', 'acc', 'ad', 'adlah', 'adlh', 'adoh', 'afaik', 'aha', 'ahaha', 'aing', 'aj', 'aja', 'ajep-ajep', 'ajj', 'ak', 'aka', 'akika', 'akko', 'akkoh', 'akku', 'akuwh', 'akyu', 'alay', 'aljasa', 'alow', 'ama', 'ambilin', 'ambl', 'ancur', 'anjir', 'anjrit', 'ank', 'anter', 'ap', 'ap2', 'apaan', 'apasih', 'ape', 'apes', 'aplot', 'aps', 'apva', 'aq', 'aqu', 'aquwh', 'asap', 'asbun', 'aseek', 'aseekk', 'asek', 'asekk', 'aseknya', 'asem', 'asoy', 'aspal', 'astrojim', 'astul', 'ath', 'ato', 'atuh', 'au ah', 'ava', 'awak', 'aws', 'ay', 'ayang', 'ayank', 'ayok', 'b4', 'bacot', 'bakalan', 'bales', 'bandes', 'bangdes', 'bangedh', 'bangkotan', 'banpol', 'banpres', 'banpur', 'bansarkas', 'basbang', 'bazis', 'bcanda', 'bcoz', 'bdg', 'beb', 'begajulan', 'bejibun', 'beliin', 'belom', 'bencong', 'bener', 'bentar', 'ber2', 'ber3', 'berdikari', 'beresin', 'bet', 'bete', 'beti', 'beud', 'beut', 'bg', 'bgd', 'bgmn', 'bgs', 'bgt', 'bhubu', 'bijimane', 'bimbul

In [33]:
post_set = set(comments['post_id'].astype(str))
comments_df = pd.DataFrame(columns=['post_id', 'message'])

# membuat dataframe baru
for i in post_set:
  # ambil 10 comment saja
  for j in range(10):
    comments_df = comments_df.append({'post_id': i, 'message': comments[comments['post_id'].astype(str) == i]['message'].values[j]}, ignore_index=True)

comments_df

preprocess = []

for i in range(len(comments_df['message'])):
  # CASE FOLDING
  # hapus punctuation dan emoji
  review = re.sub('[^a-zA-Z]', ' ', comments_df['message'][i])
  # jadi lowercase
  review = review.lower()
  # hapus tanda baca
  translator = str.maketrans('','', string.punctuation)
  review = review.translate(translator)
  # hapus extra spasi
  review = review.strip()

  # FILTERING (Stopword Removal) dengan Sastranawi
  data = stop_factory + more_stopword #menggabungkan stopword
  dictionary = ArrayDictionary(data)
  data_kata = StopWordRemover(dictionary)
  stop = data_kata.remove(review)

  # TOKENIZING
  # memisahkan kalimat per kata 
  tokens = nltk.tokenize.word_tokenize(stop)
  # detect kemunculan frequency token -> print(frequensi.most_common())
  frequensi = nltk.FreqDist(tokens)
  # menggabungkan tokens
  preprocess.append(tokens)

print(preprocess)

[['terima', 'kasih', 'banyak', 'atas', 'semua', 'tetap', 'berfikir', 'positif', 'semangat', 'pandemi', 'segera', 'berakhir', 'jaga', 'jarak', 'minimal'], ['ayo', 'bantu', 'pemerintah', 'cara', 'melaksanakan', 'protokol', 'kesehatan', 'pakai', 'masker', 'jaga', 'jarak', 'hindari', 'kerumunan', 'banyak', 'orang', 'sering', 'cuci', 'tangan', 'semakin', 'patuh', 'masyarakat', 'nya', 'melakukan', 'protokol', 'kesehatan', 'semuan', 'cepat', 'keluar', 'musibah', 'covid', 'aamiin', 'semoga', 'cepat', 'kepercayaan', 'negara', 'asing', 'expor', 'kita', 'bisa', 'jalan', 'ekonomi', 'berputar', 'salam', 'buat', 'semuanya'], ['pemerintah', 'berusaha', 'semaksimal', 'mungkin', 'memutus', 'rantai', 'virus', 'bahkan', 'geram', 'menangani', 'pandemi', 'tinggal', 'kitanya', 'masyarakat', 'bantu', 'pemerintah', 'jangan', 'saling', 'menyalahkan', 'dimulai', 'diri', 'kita', 'sendiri', 'jaga', 'kesehatan'], ['kalau', 'aplikasi', 'mata', 'kuliah', 'akuntansi', 'nakes', 'meraih', 'laba', 'pengeluaran', 'sembuh

# **Semantic Analysis**

## **Memuat Daftar Kata**

In [34]:
word_list = {}
for i in range(0, len(preprocess)):
    word_token = preprocess[i]
    # Mengecek setiap token
    for token in word_token:
        # Token yang tidak ditemukan pada word_list bernilai 0
        if token not in word_list:
            word_list[token] = 0
        else:
            word_list[token] += 1

sorted_word_list = {k: v for k, v in sorted(word_list.items(), key = lambda item: item[1], reverse = True)}
print(sorted_word_list)

{'semoga': 46, 'banyak': 32, 'semua': 31, 'covid': 31, 'pandemi': 26, 'allah': 24, 'berakhir': 23, 'cepat': 23, 'tetap': 22, 'jaga': 22, 'corona': 20, 'kesehatan': 19, 'orang': 19, 'buat': 18, 'positif': 17, 'semangat': 17, 'selalu': 17, 'pemerintah': 16, 'medis': 16, 'ada': 16, 'kalian': 15, 'masyarakat': 13, 'nya': 13, 'jangan': 13, 'korona': 13, 'kasih': 12, 'atas': 12, 'negara': 12, 'virus': 12, 'melindungi': 12, 'indonesia': 12, 'jarak': 11, 'protokol': 11, 'kita': 11, 'berdoa': 11, 'biasa': 11, 'mati': 11, 'di': 10, 'kerja': 10, 'masker': 9, 'diri': 9, 'luar': 9, 'yg': 9, 'sehat': 9, 'kan': 9, 'segera': 8, 'sendiri': 8, 'sembuh': 8, 'paling': 8, 'sangat': 8, 'dan': 8, 'penyakit': 8, 'anak': 8, 'semakin': 7, 'berusaha': 7, 'menyalahkan': 7, 'berpikir': 7, 'amin': 7, 'vaksin': 7, 'terus': 7, 'aamiinn': 7, 'terima': 6, 'bisa': 6, 'mungkin': 6, 'saling': 6, 'terutama': 6, 'pengorbanan': 6, 'berjasa': 6, 'garda': 6, 'tugas': 6, 'sakit': 6, 'normal': 6, 'berfikir': 5, 'minimal': 5, 'ba

In [35]:
len(word_list)

1131

## **Mengimpor Data Leksikon**

In [36]:
path = "/content/drive/MyDrive/Project Sistem Pakar/modified_full_lexicon.csv"

# Membaca data leksikon
dict = pd.read_csv(path)

negation_words = ['bukan','tidak','ga','gk']

# Menghapus data yang termasuk kata negasi
dict = dict.drop(dict[(dict['word'] == 'bukan') | (dict['word'] == 'tidak') | (dict['word'] == 'ga') | (dict['word'] == 'gk')].index, axis=0)

# Menyetel ulang indeks data
dict = dict.reset_index(drop=True)

dict.head(10)

word  weight  number_of_words
0        hai       3                1
1    merekam       2                1
2  ekstensif       3                1
3  paripurna       1                1
4     detail       2                1
5     pernik       3                1
6      belas       2                1
7      welas       4                1
8     kabung       1                1
9     rahayu       4                1

In [37]:
len(dict)

10248

In [38]:
dict['weight'].value_counts()

-3    2565
-4    1975
 3    1345
-5    1277
 4     867
 2     660
-2     576
 1     543
-1     260
 5     180
Name: weight, dtype: int64

In [39]:
dict['number_of_words'].value_counts()

1    9536
2     686
3      24
4       2
Name: number_of_words, dtype: int64

## **Menampilkan Daftar Kata yang Tidak Ditemukan pada Data Leksikon**

In [40]:
# Menginisialisasi stemmer
stemmer_factory = StemmerFactory()
stemmer = stemmer_factory.create_stemmer()

In [41]:
dict_list = dict['word'].values.tolist()
not_included_words = []
for word in word_list.keys():
    # Kata yang tidak ditemukan pada dict_list
    if word not in dict_list:
        # Stemming
        kata_dasar = stemmer.stem(word)
        # Kata dasar yang tidak ditemukan pada dict_list ditambahkan pada not_included_words
        if kata_dasar not in dict_list:
            not_included_words.append(word)

print(not_included_words)

['berfikir', 'berakhir', 'pemerintah', 'cara', 'protokol', 'pakai', 'masker', 'hindari', 'kerumunan', 'orang', 'cuci', 'masyarakat', 'nya', 'melakukan', 'covid', 'negara', 'asing', 'expor', 'kita', 'bisa', 'jalan', 'ekonomi', 'berputar', 'salam', 'virus', 'bahkan', 'geram', 'kitanya', 'saling', 'akuntansi', 'nakes', 'pemasukan', 'jumlah', 'terkendali', 'medis', 'kalian', 'luar', 'paling', 'depan', 'selalu', 'vaksin', 'corona', 'nambah', 'terus', 'penerusnya', 'pemimpin', 'lunasin', 'berprestasi', 'rakyatnya', 'kesejahteraan', 'indonesia', 'material', 'oknum', 'mempecah', 'bela', 'pribumi', 'tante', 'princes', 'mirabella', 'siang', 'dijalan', 'dorong', 'motor', 'bannya', 'barunya', 'smbil', 'tambal', 'ban', 'amiiiin', 'waow', 'ribuan', 'yg', 'prnh', 'expose', 'liput', 'gtu', 'gjla', 'smua', 'ayam', 'tadi', 'dong', 'rakyat', 'tni', 'daya', 'swt', 'allahu', 'akbar', 'seluruh', 'jajarannya', 'pahlawan', 'maximal', 'polres', 'banjarnegara', 'program', 'sarsipol', 'kaca', 'geothermal', 'jath

In [42]:
len(not_included_words)

604

In [43]:
# Kata yang tidak ditemukan dan muncul lebih dari 3 kali 
not_included_list = {k: v for (k, v) in word_list.items() if ((k in not_included_words) & (v > 3))}

# Mengurutkan not_included_list berdasarkan jumlah kemunculan terbanyak
sort_items = sorted(not_included_list.items(), key = lambda x: x[1], reverse = True)

# Mengambil 20 nilai not_included_list pertama
sort_items = sort_items[0:20]

# Menampilkan not_included_list yang telah diurutkan
for i in sort_items:
    print(i[0], i[1])

covid 31
berakhir 23
corona 20
orang 19
selalu 17
pemerintah 16
medis 16
kalian 15
masyarakat 13
nya 13
korona 13
negara 12
virus 12
indonesia 12
protokol 11
kita 11
di 10
masker 9
luar 9
yg 9


## **Menghitung Nilai Sentimen**

In [44]:
# Fungsi untuk menghitung nilai sentimen
def calculate_sentiment(index, word_token, word, sentiment):
    # Kata yang terdapat negation_words dibelakangnya memiliki nilai sentimen yang negatif
    if (word_token[index-1] in negation_words):
        sentiment += -dict['weight'][dict_list.index(word)]
    # Menambahkan nilai sentimen
    else:
        sentiment += dict['weight'][dict_list.index(word)]
    
    return sentiment

In [45]:
sentiment_list = []

# Menghitung nilai sentimen setiap kalimat
for i in range(0, len(preprocess)):
    sentiment = 0 
    word_token = preprocess[i]
    
    # Mengecek token pada setiap kalimat
    for token in word_token:
        index = word_token.index(token)
        # Menghitung sentimen pada token yang terdapat pada data leksikon
        if token in dict_list :
            sentiment = calculate_sentiment(index, word_token, token, sentiment)
        else:
            kata_dasar = stemmer.stem(token)
            # Mengecek kata dasar dari token jika tidak terdapat pada data leksikon
            if kata_dasar in dict_list:
                sentiment = calculate_sentiment(index, word_token, kata_dasar, sentiment)
            # Mengecek kombinasi kata dengan kata sebelumnya
            elif(len(word_token) > 1):
                # Kombinasi dengan satu kata sebelumnya
                if(index-1 > -1):
                    combination_one = word_token[index-1] + ' ' + token
                    if (combination_one in dict_list):
                        sentiment= calculate_sentiment(index, word_token, combination_one, sentiment)
                    # Kombinasi dengan dua kata sebelumnya
                    elif(index-2 > -1):
                        combination_two = word_token[index-2] + ' ' + combination_one
                        if combination_two in dict_list:
                            sentiment= calculate_sentiment(index, word_token, combination_two, sentiment)
    
    sentiment_list.append(sentiment)

# Menampilkan seluruh nilai sentimen
print(sentiment_list)

[11, 35, 1, -1, 11, 45, -6, 40, 14, 28, 17, 29, 1, 4, 11, 16, 5, 35, 9, 2, 45, 37, 14, 12, 18, 6, 8, -2, 7, 10, 45, 11, 10, 2, -5, 23, 19, 12, 10, -2, 18, 11, -10, 5, -11, 9, 45, 12, 14, 8, -1, 39, -29, 11, -10, 1, 3, 40, 27, 17, 37, -5, 16, 11, -3, 11, 29, 14, 23, 22, 25, 6, -3, 22, -5, -1, 12, 11, 1, -27, 37, -1, 25, 10, -3, 3, 11, 14, -21, 21, 11, -1, 37, 14, 32, 12, 7, 19, -6, 0]


In [46]:
# Membuat matriks 2 dimensi, dimana -1 artinya jumlah baris akan dikalkulasikan secara otomatis untuk setiap 10 value
print(np.array(sentiment_list).reshape(-1, 10))

[[ 11  35   1  -1  11  45  -6  40  14  28]
 [ 17  29   1   4  11  16   5  35   9   2]
 [ 45  37  14  12  18   6   8  -2   7  10]
 [ 45  11  10   2  -5  23  19  12  10  -2]
 [ 18  11 -10   5 -11   9  45  12  14   8]
 [ -1  39 -29  11 -10   1   3  40  27  17]
 [ 37  -5  16  11  -3  11  29  14  23  22]
 [ 25   6  -3  22  -5  -1  12  11   1 -27]
 [ 37  -1  25  10  -3   3  11  14 -21  21]
 [ 11  -1  37  14  32  12   7  19  -6   0]]


In [47]:
average_sentiment = np.mean(np.array(sentiment_list).reshape(-1, 10), axis=1)
print(average_sentiment)

[17.8 12.9 15.5 12.5 10.1  9.8 15.5  4.1  9.6 12.5]


In [48]:
df['sentimen_val'] = average_sentiment

In [49]:
df.head(10)

post_id  ... sentimen_val
0  4004976832865720  ...         17.8
1  4004494309580639  ...         12.9
2  4004417006255036  ...         15.5
3  4004358039594266  ...         12.5
4  4003974322965971  ...         10.1
5  4003663296330407  ...          9.8
6  4002335383129865  ...         15.5
7  4001694956527241  ...          4.1
8  4001626216534115  ...          9.6
9  4000645779965492  ...         12.5

[10 rows x 9 columns]

# **Matriks Keputusan**

In [50]:
durasi_berita_list = []
for index, value in df['time'].items():
  waktu_post_berita = datetime.strptime(value, '%Y-%m-%d %H:%M:%S')
  waktu_sekarang = datetime.now()
  durasi_berita = (waktu_sekarang - waktu_post_berita)
  # durasi berita dalam hari
  durasi_berita_list.append(durasi_berita.total_seconds() / (60 * 60 * 24))

print(durasi_berita_list)

[11.096697960011573, 11.269197960717593, 11.30045953508102, 11.323746572349538, 11.449498887395833, 11.555667869108797, 11.994244258194446, 12.199406295439815, 12.225274351215278, 12.581813703506944]


In [51]:
df['durasi_berita'] = durasi_berita_list

In [52]:
# likes, comment, share, nilai sentimen, durasi berita
decision_matrix = df[['likes', 'comments', 'shares', 'sentimen_val', 'durasi_berita']].copy()
decision_matrix.head(10)

likes  comments  shares  sentimen_val  durasi_berita
0   63636      1285       0          17.8      11.096698
1  263654       646     332          12.9      11.269198
2  106157       308     135          15.5      11.300460
3    1042        19       0          12.5      11.323747
4  197659      1303     459          10.1      11.449499
5    2833        49       0           9.8      11.555668
6  222208       733     478          15.5      11.994244
7  170032      1874     588           4.1      12.199406
8   73346      1489       0           9.6      12.225274
9   63068       714       0          12.5      12.581814

In [53]:
# returns a numpy array
x = decision_matrix.values 
min_max_scaler = preprocessing.MinMaxScaler(feature_range=(1, 5))
x_scaled = min_max_scaler.fit_transform(x)
scaled_decision_matrix = pd.DataFrame(x_scaled, columns=['likes', 'comments', 'shares', 'sentimen_val', 'durasi_berita'])
scaled_decision_matrix.head(10)

likes  comments    shares  sentimen_val  durasi_berita
0  1.953407  3.729919  1.000000      5.000000       1.000000
1  5.000000  2.352022  3.258503      3.569343       1.464610
2  2.601069  1.623181  1.918367      4.328467       1.548810
3  1.000000  1.000000  1.000000      3.452555       1.611531
4  3.994791  3.768733  4.122449      2.751825       1.950231
5  1.027280  1.064690  1.000000      2.664234       2.236186
6  4.368711  2.539623  4.251701      4.328467       3.417445
7  3.573987  5.000000  5.000000      1.000000       3.970027
8  2.101305  4.169811  1.000000      2.605839       4.039699
9  1.944755  2.498652  1.000000      3.452555       5.000000

In [54]:
mtx = scaled_decision_matrix.to_numpy()
mtx

array([[1.95340655, 3.72991914, 1.        , 5.        , 1.        ],
       [5.        , 2.35202156, 3.2585034 , 3.56934307, 1.46461025],
       [2.60106926, 1.62318059, 1.91836735, 4.32846715, 1.54880995],
       [1.        , 1.        , 1.        , 3.45255474, 1.61153109],
       [3.99479079, 3.76873315, 4.12244898, 2.75182482, 1.95023147],
       [1.02727979, 1.06469003, 1.        , 2.66423358, 2.23618623],
       [4.36871125, 2.53962264, 4.25170068, 4.32846715, 3.41744471],
       [3.57398748, 5.        , 5.        , 1.        , 3.97002665],
       [2.10130535, 4.16981132, 1.        , 2.60583942, 4.03969949],
       [1.944755  , 2.49865229, 1.        , 3.45255474, 5.        ]])

# **MCDM AHP TOPSIS**

In [55]:
 pip install scikit-criteria

     |████████████████████████████████| 61kB 3.1MB/s 
     |████████████████████████████████| 40.6MB 96kB/s 
  Created wheel for scikit-criteria: filename=scikit_criteria-0.2.10-cp36-none-any.whl size=118313 sha256=199e083eb9ed403c43938279b9a767c60c01016c2ae752e28764c3a2f5510b9b
  Stored in directory: /root/.cache/pip/wheels/57/ed/90/3dfef98b07189ad37e6ff7fb94285672430929173dca968bc5
Successfully built scikit-criteria


In [56]:
from skcriteria import Data, MIN, MAX

## **AHP**

In [57]:
# Initialize Data
matrix = [[1, 1/5, 3, 1/7, 3],
          [5, 1, 5, 1/3, 3],
          [1/3, 1/5, 1, 1/7, 1/3],
          [7, 3, 7, 1, 7],
          [1/3, 1/3, 3, 1/7, 1]]
row    = 5 #Jumlah baris
column = 5 #Jumlah kolom
criteria = [MAX, MAX, MAX, MAX, MIN]
alternativeName=["C1", "C2", "C3", "C4", "C5"]
criteriaName=["C1", "C2", "C3", "C4", "C5"] 				

#Ubah value matrix menjadi float
floatMatrix = []
for i in matrix:
  try:
    ix=[]
    for j in i:
      ix.append(float(j))
  except:
    ix=float(i)
    pass
  floatMatrix.append(ix)

data = Data (floatMatrix, criteria, anames=alternativeName, cnames=criteriaName)
data

ALT./CRIT.    C1 (max)    C2 (max)    C3 (max)    C4 (max)    C5 (min)
------------  ----------  ----------  ----------  ----------  ----------
     C1           1          0.2          3        0.142857       3
     C2           5           1           5        0.333333       3
     C3        0.333333      0.2          1        0.142857    0.333333
     C4           7           3           7           1           7
     C5        0.333333    0.333333       3        0.142857       1

In [58]:
tempMtx = floatMatrix
total=np.array([np.sum(tempMtx,axis=0)])
tempMtx=np.concatenate((tempMtx,total),axis=0)

alternativeName=["C1", "C2", "C3", "C4", "C5", "Total"]
data = Data (tempMtx, criteria, anames=alternativeName, cnames=criteriaName)
data

ALT./CRIT.    C1 (max)    C2 (max)    C3 (max)    C4 (max)    C5 (min)
------------  ----------  ----------  ----------  ----------  ----------
     C1           1          0.2          3        0.142857       3
     C2           5           1           5        0.333333       3
     C3        0.333333      0.2          1        0.142857    0.333333
     C4           7           3           7           1           7
     C5        0.333333    0.333333       3        0.142857       1
   Total       13.6667     4.73333        19        1.7619     14.3333

### **Step 1:** Normalisasi Matrix Pairwise & Mencari Weight

In [59]:
#Normalisasi Matrix
normMtx=[]
for i in range(row):
  try:
    ix=[]
    for j in range(column):
      ix.append(floatMatrix[i][j]/total[0][j])
  except:
    ix=i
    pass
  normMtx.append(ix)

tempMtx = normMtx
w=np.array([np.average(tempMtx,axis=1)])
tempMtx=np.concatenate((tempMtx,w.T),axis=1)

criteria = [MAX, MAX, MAX, MAX, MIN, MAX]
alternativeName=["C1", "C2", "C3", "C4", "C5"]
criteriaName=["C1", "C2", "C3", "C4", "C5", "weight"] 
data = Data (tempMtx, criteria, anames=alternativeName, cnames=criteriaName)
print("Normalize Matrix")
data

Normalize Matrix


ALT./CRIT.    C1 (max)    C2 (max)    C3 (max)    C4 (max)    C5 (min)    weight (max)
------------  ----------  ----------  ----------  ----------  ----------  --------------
     C1       0.0731707   0.0422535    0.157895   0.0810811    0.209302      0.11274
     C2        0.365854    0.211268    0.263158    0.189189    0.209302      0.247754
     C3       0.0243902   0.0422535   0.0526316   0.0810811   0.0232558     0.0447224
     C4        0.512195    0.633803    0.368421    0.567568    0.488372      0.514072
     C5       0.0243902   0.0704225    0.157895   0.0810811   0.0697674     0.0807112

### **Step 2:** Mengecek CR dari Matriks Pairwise

In [60]:
AX = np.matmul(floatMatrix, np.transpose(w))
AX

array([[0.61203109],
       [1.44855964],
       [0.23219599],
       [2.92455308],
       [0.40848224]])

### **Step 3:** Menghitung Consistency Vector



In [61]:
c_vector = np.true_divide(AX, np.transpose(w))
c_vector

array([[5.42867208],
       [5.84676271],
       [5.19193382],
       [5.68899806],
       [5.06103492]])

### **Step 4:** Mencari Lambda, CI, CR


In [62]:
lambdaMax = c_vector.mean()
CI = (lambdaMax-column)/(column-1)
RI = 1.12
CR = CI/RI

print("Lambda Max = ",lambdaMax)
print("CI = ",CI)
print("CR = ",CR, " < 0.1 = konsisten")

Lambda Max =  5.443480317747239
CI =  0.11087007943680982
CR =  0.09899114235429447  < 0.1 = konsisten


## **TOPSIS**

In [63]:
# Initialize Data
row    = 10 #Jumlah baris
column = 5 #Jumlah kolom
criteria = [MAX, MAX, MAX, MAX, MIN]
alternativeName=["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
criteriaName=["likes", "comments", "shares", "sentimen_val", "durasi_berita"] 				

#Ubah value matrix menjadi float
floatMtx = []
for i in mtx:
  try:
    ix=[]
    for j in i:
      ix.append(float(j))
  except:
    ix=float(i)
    pass
  floatMtx.append(ix)

data = Data (floatMtx, criteria, anames=alternativeName, cnames=criteriaName)
data

ALT./CRIT.    likes (max)    comments (max)    shares (max)    sentimen_val (max)    durasi_berita (min)
------------  -------------  ----------------  --------------  --------------------  ---------------------
     0           1.95341         3.72992             1                  5                      1
     1              5            2.35202           3.2585            3.56934                1.46461
     2           2.60107         1.62318          1.91837            4.32847                1.54881
     3              1               1                1               3.45255                1.61153
     4           3.99479         3.76873          4.12245            2.75182                1.95023
     5           1.02728         1.06469             1               2.66423                2.23619
     6           4.36871         2.53962           4.2517            4.32847                3.41744
     7           3.57399            5                5                  1                   3.97003
     8           2.10131         4.16981             1               2.60584                4.0397
     9           1.94475         2.49865             1               3.45255                   5

### **Step 1 :** Normalisasi Decision Matrix

In [64]:
criteria = [MAX, MAX, MAX, MAX, MIN]
criteriaName=["likes", "comments", "shares", "sentimen_val", "durasi_berita"] 

#Transpose matrix
mtxTrans = np.transpose(floatMtx)

#Menguadratkan nilai matrix
powerMtx=[]
for i in mtxTrans:
  try:
    ix=[]
    for j in i:
      ix.append(pow(j,2))
  except:
    ix=i
    pass
  powerMtx.append(ix)

#Normalisasi Matrix
rij=[]
for i in range(row):
  try:
    ix=[]
    for j in range(column):
      ix.append(floatMtx[i][j]/pow(sum(powerMtx[j]),(1/2)))
  except:
    ix=i
    pass
  rij.append(ix)
  
print("Normalize Matrix")
pd.DataFrame(rij, columns=criteriaName)

Normalize Matrix


likes  comments    shares  sentimen_val  durasi_berita
0  0.201853  0.385747  0.112247      0.453585       0.108019
1  0.516669  0.243245  0.365756      0.323800       0.158205
2  0.268778  0.167869  0.215330      0.392666       0.167301
3  0.103334  0.103420  0.112247      0.313206       0.174076
4  0.412797  0.389761  0.462731      0.249637       0.210662
5  0.106153  0.110110  0.112247      0.241691       0.241550
6  0.451436  0.262647  0.477239      0.392666       0.369148
7  0.369314  0.517098  0.561233      0.090717       0.428837
8  0.217136  0.431240  0.112247      0.236394       0.436363
9  0.200959  0.258410  0.112247      0.313206       0.540094

### **Step 2 :** Menghitung Bobot Decision Matrix

In [65]:
weight=[]
for i in range(len(w[0])):
  try:
    ix=[]
    for j in range(len(w[0])):
      if(i==j):
        ix.append(w[0][j])
      else:
        ix.append(0)
  except:
    ix=i
    pass
  weight.append(ix)

#Vij = Wj*rij
vij = []
vij = np.matmul(rij,weight)
pd.DataFrame(vij, columns=criteriaName)

likes  comments    shares  sentimen_val  durasi_berita
0  0.022757  0.095570  0.005020      0.233175       0.008718
1  0.058250  0.060265  0.016357      0.166457       0.012769
2  0.030302  0.041590  0.009630      0.201858       0.013503
3  0.011650  0.025623  0.005020      0.161010       0.014050
4  0.046539  0.096565  0.020694      0.128332       0.017003
5  0.011968  0.027280  0.005020      0.124247       0.019496
6  0.050895  0.065072  0.021343      0.201858       0.029794
7  0.041637  0.128113  0.025100      0.046635       0.034612
8  0.024480  0.106842  0.005020      0.121524       0.035219
9  0.022656  0.064022  0.005020      0.161010       0.043592

### **Step 3 :** Menghitung solusi ideal positif dan negatif

In [66]:
A_Positif=[]
A_Negatif=[]
for i in range(column):
  if criteria[i]==1:
    A_Positif.append(max(vij[:,i]))
    A_Negatif.append(min(vij[:,i]))
  else:
    A_Positif.append(min(vij[:,i]))
    A_Negatif.append(max(vij[:,i]))

print("Positive Ideal (A*)")
print(A_Positif)
print("\n")
print("Negative Ideal (A')")
print(A_Negatif)

Positive Ideal (A*)
[0.058249511647696844, 0.1281132133494298, 0.025099709086756638, 0.23317537705923663, 0.00871832629874616]


Negative Ideal (A')
[0.01164990232953937, 0.025622642669885957, 0.005019941817351328, 0.04663507541184733, 0.04359163149373079]


### **Step 4 :** Menghitung Nilai Separasi

In [67]:
pembagi_Positif=(vij - A_Positif)**2
pembagi_Negatif=(vij - A_Negatif)**2

S_Positif=[]
S_Negatif=[]
for j in range(row):
  S_Positif.append(sum(pembagi_Positif[j,:])**0.5)
  S_Negatif.append(sum(pembagi_Negatif[j,:])**0.5)

print("Positive Ideal (S*)")
print(S_Positif)
print("\n")
print("Negative Ideal (S')")
print(S_Negatif)

Positive Ideal (S*)
[0.05217232425940173, 0.0956431401198817, 0.09752047983331032, 0.13533396756577779, 0.11051107738956044, 0.15714358972618467, 0.07394164804945579, 0.18906018752962703, 0.12314424291420013, 0.1104614041158229]


Negative Ideal (S')
[0.20255736413106631, 0.13714003287285928, 0.1600741262281512, 0.11812863544242198, 0.11780077247409285, 0.08128362044295132, 0.1662754196895942, 0.10902912672292377, 0.11153251036576536, 0.12114996075937103]


### **Step 5 :** Menghitung Solusi Relatif Terdekat dengan Solusi Ideal

In [68]:
np.seterr(all='ignore')
S_Positif=np.array(S_Positif)
S_Negatif=np.array(S_Negatif)
c=S_Negatif/(S_Positif+S_Negatif)
# print("{}{}".format("C* = ", c))

x=0
m=0.0
for i in range(row):
  if c[i]>m or m==None:
    m=c[i]
    x=i
# print ('\n',df['text'][x],'is the best alternative = ',c[x], '\n')
df_c = pd.DataFrame(df['text'], columns=["text"])
df_c['c*'] = pd.DataFrame(c, columns=["c*"])
df_c['rank'] = pd.DataFrame(c, columns=["rank"]).rank(ascending=False)
df_c

text        c*  rank
0  #Update Perkembangan COVID-19 di Indonesia per...  0.795186   1.0
1  Stafsus Daniel Tinjau Kesiapan Rumkit TNI AD S...  0.589132   4.0
2  Peroleh Rekor Muri, Layanan PSC 119 di Sumsel ...  0.621419   3.0
3  Rakornas KKI: Meningkatkan profesionalisme dok...  0.466059   8.0
4  Protokol Kesehatan Ketat Percepat Pemulihan Ke...  0.515964   6.0
5  Selamat Pagi #Healthies\n\nAkhir-akhir ini beb...  0.340916  10.0
6  RSUD Buleleng Mampu Tes PCR Mandiri\n\nBali, 2...  0.692188   2.0
7  Perbaiki Sektor Pariwisata di Masa Pandemi COV...  0.365760   9.0
8  #Update Perkembangan COVID-19 di Indonesia per...  0.475260   7.0
9  Hai #Healthies\n\nSaat ini di Indonesia ada se...  0.523074   5.0

## **Perhitungan Akurasi**

In [81]:
rank_list = df_c['rank'].tolist()
y_pred = [round(rank) for rank in rank_list]
y_true = [1, 4, 3, 6, 8, 10, 2, 9, 7, 5]

print('hasil prediksi :', y_pred)
print('pakar          :', y_true)

hasil prediksi : [1, 4, 3, 8, 6, 10, 2, 9, 7, 5]
pakar          : [1, 4, 3, 6, 8, 10, 2, 9, 7, 5]


In [82]:
accuracy_score(y_true, y_pred)

0.8